system: "regulatory_expert" #regulatory_expert, general_expert, md_class, clinical_evaluation_expert
mode: "interactive" #interactive, eval, curate_dataset, test_md_class

pdf_path: '/mnt/c/Users/pc/Documents/complAI/Training materials for models/'

reader:
  provider: "PyPDF" #PyPDF, PyMuPDF, LLamaParse, Unstructured
  file_type: "PDF" #Markdown, PDF

chunking:
  type: "recursive" #simple, recursive, semantic, agentic, contextual
  chunk_size: 1000
  chunk_overlap: 200

embeddings:
  model: "text-embedding-3-small" #"hkunlp/instructor-xl", dunzhang/stella_en_400M_v5, abhinand/MedEmbed-large-v0.1, meta-llama/Llama-3.2-3B, text-embedding-3-small, emilyalsentzer/Bio_ClinicalBERT, NeuML/pubmedbert-base-embeddings, Zybg/synthetic-clinical-embedding-model, medicalai/ClinicalBERT
  provider: "OpenAI" #HuggingFace, OpenAI

vectorstore:
  provider: "Milvus"
  new: False

models:
  generation:
    name: "gpt-4o-mini" #"mistralai/Mistral-7B-Instruct-v0.3", meta-llama/Llama-3.2-3B-Instruct, "llama-3.3-70b-versatile"
    provider: "OpenAI" #HuggingFace, OpenAI, Groq, TogetherAI
    temperature: 0.5
  rewriting:
    name: "gpt-4o-mini" #"mistralai/Mistral-7B-Instruct-v0.3", meta-llama/Llama-3.2-3B-Instruct, "llama-3.3-70b-versatile"
    provider: "OpenAI" #HuggingFace, OpenAI, Groq, TogetherAI
    temperature: 0.5
  retrieve:
    name: "gpt-4o-mini" #"mistralai/Mistral-7B-Instruct-v0.3", meta-llama/Llama-3.2-3B-Instruct, "llama-3.3-70b-versatile"
    provider: "OpenAI" #HuggingFace, OpenAI, Groq, TogetherAI
    temperature: 0.5
  eval:
    name: "gpt-4o-mini" #"mistralai/Mistral-7B-Instruct-v0.3", meta-llama/Llama-3.2-3B-Instruct, "llama-3.3-70b-versatile", "together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
    provider: "OpenAI" #HuggingFace, OpenAI, Groq, TogetherAI
    temperature: 0.5

retrieval:
  type: "base_retriever" #base_retriever, reranking_retriever, reranking_filtering_retriever, multi_query_retriever, ensemble_retriever, web_search_retriever, parent_document_retriever, keyword_retrieval
  search_type: "similarity" #similarity, mmr, similarity_score_threshold
  search_kwargs: 
    k: 20
    #fetch_k: 20
    #lambda_mult: 0.5
    #score_threshold: 0.1
  reranking:
    enabled: False
    provider: "Cohere"  # HuggingFace, Cohere
    model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2" # cross-encoder/ms-marco-MiniLM-L-6-v2, BAAI/bge-reranker-v2-m3, mixedbread-ai/mxbai-rerank-large-v1, meta-llama/Llama-3.2-3B
    top_n: 10
  filtering:
    enabled: False
    embedding_model: "hkunlp/instructor-xl"
  ensemble_retriever: ["base_retriever", "multi_query_retriever"]

rewrite_query: False

data:
  clustering: False
  rewriting: False

HyDe: False